### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by albertobenavides** [GuavaCZ/filament-drafts#1]
1. ~In the create view, clicking Save draft publish the current element model~
2. Unpublish button does not appear
3. ~After creating a draft, clicking Publish makes all elements a draft and its impossible to publish again in the same element~

**Comment by albertobenavides** [comment]
> 1. In the create view, clicking Save draft publish the current element model
> 2. Unpublish button does not appear
> 3. After creating a draft, clicking Publish makes all elements a draft and its impossible to publish again in the same element

So, issue2 number 1 and 3 are solved by adding `'is_published'` in the fillable array of the model, like this:
```
protected $fillable = [
    // ...
    'is_published'
];
```

I have not been able to resolve the second issue. My workarround was to move the `UnpublishAction::make(),` from `getActions()` to `getFormActions()` in the `Draftable.php` class of the Edit page. I ended up with something like this: 

```
protected function getActions(): array
{
    return [];
}

protected function getFormActions(): array
{
    return [
        ...array_slice(parent::getFormActions(), 0, 1),
        SaveDraftAction::make(),
        UnpublishAction::make(),
        ...array_slice(parent::getFormActions(), 1),
    ];
}
```

**Comment by lukas-frey** [comment]
Hi, thanks for the info! You're right, I forgot to mention that `is_published` has to be in the fillable array of the model.

I'm not sure whether I like having the unpublish action in the form actions instead of the page actions. What PHP version are you using?

Or I can make it configurable, so people can decide themselves whether to add it in the form or page actions.

**Comment by lukas-frey** [comment]
@albertobenavides I added a custom `HasDrafts` trait which wraps the original trait from Laravel Drafts. All it does it add `is_published` to the fillable array for you.

So now you don't need to add it manually, just use the HasDrafts trait from this package.

**Comment by albertobenavides** [comment]
@LukasFreyCZ, I have PHP version 8.1.5 and Laravel 10.7.1. I really do not know why the `UnpublishAction::make()` is not showing in the upper actions section. I like it better there, too. In any case, sounds like having the option to choose where the button is going to be, will give the user more flexibility.

Great work, btw :)

**Comment by lukas-frey** [comment]
Okay, that's weird. Should work in that case. Keep in mind though that the button should only appear when you're viewing the published version of the record.

Anyways, I merged yours, so it is now in the form actions. I will make a update soon that makes it configurable. :)

**Comment by albertobenavides** [comment]
I think this issue is pretty much solved, hehe. Thanks!
