### ISSUE TITLE
List Draft/Revisions in a separate Filament Tab

### ISSUE THREAD

**Issue by mansoorkhan96** [GuavaCZ/filament-drafts#11]
## Problem

For some reason the table actions for draft/revisions table would not work. I have tried to add them separately and also tried to allow user to pass those actions but nothing works.

## Solution

The work around for me was to use Tabs on ListRecord pages to filter records. This allowed the usage of existing actions. Other benefit of using tabs is:

- Less space on page
- Better UI
- Less code to maintain, we can remove the `list-draftable-records` view file and the livewire components it loads
- We dont need to define/pass which fields, actions and filters to load. Those will be loaded from resource itself.

The code we need:

```php
use Illuminate\Database\Eloquent\Builder;
use Filament\Resources\Pages\ListRecords\Tab;

public function getTabs(): array
{
    return [
        'all' => Tab::make()
            ->modifyQueryUsing(fn (Builder $query) => $query->withoutDrafts()),
        'drafts' => Tab::make()
            ->modifyQueryUsing(fn (Builder $query) => $query->onlyDrafts()->where('is_current', true)),
    ];
}
```

@LukasFreyCZ I am planning to send this Pull request. I need to hear your thoughts.

Thanks :)

**Comment by lukas-frey** [comment]
Thanks a lot for the PR @mansoorkhan96 ! It's being merged now. :)
