### ISSUE TITLE
 Guava\FilamentDrafts\Admin\Resources\Pages\Edit\Draftable collision.

### ISSUE THREAD

**Issue by GonrasK** [GuavaCZ/filament-drafts#14]
Hello. Great package, enjoying it so far, but on some of my multi lingual assets when using both Translatable and Draftable traits on the same EditRecord class - there is a collision error. 

Code - 

```php
<?php

namespace App\Filament\Resources\PillarResource\Pages;

use App\Filament\Resources\PillarResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Guava\FilamentDrafts\Admin\Resources\Pages\Edit\Draftable;
class EditPillar extends EditRecord
{
    use EditRecord\Concerns\Translatable;
    use Draftable;
    protected static string $resource = PillarResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
            Actions\LocaleSwitcher::make(),

        ];
    }
}

```

Results in `Trait method Guava\FilamentDrafts\Admin\Resources\Pages\Edit\Draftable::handleRecordUpdate has not been applied as App\Filament\Resources\PillarResource\Pages\EditPillar::handleRecordUpdate, because of collision with Filament\Resources\Pages\EditRecord\Concerns\Translatable::handleRecordUpdate`

**Comment by lukas-frey** [comment]
Yeah, the package doesn't work very well with the translatable package yet. One thing you can try (I'm not sure it will work, you'll need to test it), is to override the `handleRecordUpdate` method and call the method from both traits.

```php
class EditPillar extends EditRecord
{
    use EditRecord\Concerns\Translatable {
        handleRecordUpdate as handleTranslatableRecordUpdate;
    }
    use Draftable {
        handleRecordUpdate as handleDraftableRecordUpdate;
    }
    protected static string $resource = PillarResource::class;

    // your other code

    protected function handleRecordUpdate(Model $record,array $data) : Model {
        $this->handleDraftableRecordUpdate($record, $data);
        $this->handleTranslatableRecordUpdate($record, $data);
    }

}
```

Once again, I'm not sure if it's going to work as intended.

Otherwise you'll have to wait until I add support for Translatable or if you feel up to it, you are more than welcome to create a PR. :)

**Comment by GonrasK** [comment]
Thanks! It worked with a slight modification - 

```php
<?php

namespace App\Filament\Resources\PillarResource\Pages;

use App\Filament\Resources\PillarResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Guava\FilamentDrafts\Admin\Resources\Pages\Edit\Draftable;
use Filament\Resources\Pages\EditRecord\Concerns\Translatable;
class EditPillar extends EditRecord
{
    use EditRecord\Concerns\Translatable {
        Translatable::handleRecordUpdate as handleTranslatableRecordUpdate;
    }

    use Draftable {
        Draftable::handleRecordUpdate as handleDraftableRecordUpdate;
    }
    protected static string $resource = PillarResource::class;

    protected function handleRecordUpdate(Model|\Illuminate\Database\Eloquent\Model $record,array $data) : \Illuminate\Database\Eloquent\Model  {
        $this->handleDraftableRecordUpdate($record, $data);
        $this->handleTranslatableRecordUpdate($record, $data);
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
            Actions\LocaleSwitcher::make(),

        ];
    }
}

```

**Comment by GonrasK** [comment]
Whoops. It doesn't work as expected... getting an error on update events - `App\Filament\Resources\PillarResource\Pages\EditPillar::handleRecordUpdate(): Return value must be of type Illuminate\Database\Eloquent\Model, none returned`

**Comment by lukas-frey** [comment]
> Whoops. It doesn't work as expected... getting an error on update events - `App\Filament\Resources\PillarResource\Pages\EditPillar::handleRecordUpdate(): Return value must be of type Illuminate\Database\Eloquent\Model, none returned`

Oh yeah, try changing it to
```php
$record = $this->handleDraftableRecordUpdate($record, $data);
return $this->handleTranslatableRecordUpdate($record, $data);
```
