### ISSUE TITLE
It does not show/get revisions

### ISSUE THREAD

**Issue by mansoorkhan96** [GuavaCZ/filament-drafts#5]
I can created posts, publish/unpublish them etc. but the other revisions would not show up. Sometimes it also triggers an error if click on draft action on a published model.

Flare error page: https://flareapp.io/share/J7orBnxP#F59

Here is a screen-recording of the issue
[Pages---MortgageCS Admin.webm](https://user-images.githubusercontent.com/51432274/235219210-b40c492f-95f0-4817-bf7d-6b7d8dd4453a.webm)

**Comment by mansoorkhan96** [comment]
https://github.com/oddvalue/laravel-drafts/issues/27#issuecomment-1529499225

**Comment by lukas-frey** [comment]
Thanks for tracking this down. I haven't had a chance to look at it yet, but it looks like you found your issue in Laravel Drafts itself? This package only provides a UI for filament that wraps the Laravel Drafts package.

**Comment by mansoorkhan96** [comment]
@LukasFreyCZ You are right! Issue belongs Laravel drafts. 

Thanks for all the work man.
