### ISSUE TITLE
Option/Feature to modify drafts query results

### ISSUE THREAD

**Issue by mansoorkhan96** [GuavaCZ/filament-drafts#6]
Great package, works like a charm.

A humble/request: Is it possible to provide a way to extend or modify the table query for drafts table?

**Comment by lukas-frey** [comment]
> Great package, works like a charm.
> 
> A humble/request: Is it possible to provide a way to extend or modify the table query for drafts table?

Thanks for the suggestion. That should be possible, I will implement is as soon as I can. :)

**Comment by mansoorkhan96** [comment]
#7
